services:
  api:
    build: .
    container_name: "help-desk-api"
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/${DB_NAME}
    depends_on:
      - database
      - minio
    networks:
      - help_desk_network

  database:
    image: postgres:16-alpine
    container_name: help-desk_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - help_desk_network
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"
    networks:
      - help_desk_network
networks:
  help_desk_network:
    driver: bridge

volumes:
  postgres_data:
